// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeResp.proto

package com.three.core.protobuf;

public final class SubcribeRespProto {
  private SubcribeRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubcribeRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SubcribeResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 msgCode = 1;</code>
     */
    boolean hasMsgCode();
    /**
     * <code>required int32 msgCode = 1;</code>
     */
    int getMsgCode();

    /**
     * <code>required string jsonBody = 3;</code>
     */
    boolean hasJsonBody();
    /**
     * <code>required string jsonBody = 3;</code>
     */
    java.lang.String getJsonBody();
    /**
     * <code>required string jsonBody = 3;</code>
     */
    com.google.protobuf.ByteString
        getJsonBodyBytes();
  }
  /**
   * Protobuf type {@code SubcribeResp}
   */
  public  static final class SubcribeResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SubcribeResp)
      SubcribeRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubcribeResp.newBuilder() to construct.
    private SubcribeResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubcribeResp() {
      msgCode_ = 0;
      jsonBody_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubcribeResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgCode_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              jsonBody_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.three.core.protobuf.SubcribeRespProto.internal_static_SubcribeResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.three.core.protobuf.SubcribeRespProto.internal_static_SubcribeResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.three.core.protobuf.SubcribeRespProto.SubcribeResp.class, com.three.core.protobuf.SubcribeRespProto.SubcribeResp.Builder.class);
    }

    private int bitField0_;
    public static final int MSGCODE_FIELD_NUMBER = 1;
    private int msgCode_;
    /**
     * <code>required int32 msgCode = 1;</code>
     */
    public boolean hasMsgCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msgCode = 1;</code>
     */
    public int getMsgCode() {
      return msgCode_;
    }

    public static final int JSONBODY_FIELD_NUMBER = 3;
    private volatile java.lang.Object jsonBody_;
    /**
     * <code>required string jsonBody = 3;</code>
     */
    public boolean hasJsonBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string jsonBody = 3;</code>
     */
    public java.lang.String getJsonBody() {
      java.lang.Object ref = jsonBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jsonBody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string jsonBody = 3;</code>
     */
    public com.google.protobuf.ByteString
        getJsonBodyBytes() {
      java.lang.Object ref = jsonBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJsonBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jsonBody_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jsonBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.three.core.protobuf.SubcribeRespProto.SubcribeResp)) {
        return super.equals(obj);
      }
      com.three.core.protobuf.SubcribeRespProto.SubcribeResp other = (com.three.core.protobuf.SubcribeRespProto.SubcribeResp) obj;

      boolean result = true;
      result = result && (hasMsgCode() == other.hasMsgCode());
      if (hasMsgCode()) {
        result = result && (getMsgCode()
            == other.getMsgCode());
      }
      result = result && (hasJsonBody() == other.hasJsonBody());
      if (hasJsonBody()) {
        result = result && getJsonBody()
            .equals(other.getJsonBody());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgCode()) {
        hash = (37 * hash) + MSGCODE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgCode();
      }
      if (hasJsonBody()) {
        hash = (37 * hash) + JSONBODY_FIELD_NUMBER;
        hash = (53 * hash) + getJsonBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.three.core.protobuf.SubcribeRespProto.SubcribeResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SubcribeResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SubcribeResp)
        com.three.core.protobuf.SubcribeRespProto.SubcribeRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.three.core.protobuf.SubcribeRespProto.internal_static_SubcribeResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.three.core.protobuf.SubcribeRespProto.internal_static_SubcribeResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.three.core.protobuf.SubcribeRespProto.SubcribeResp.class, com.three.core.protobuf.SubcribeRespProto.SubcribeResp.Builder.class);
      }

      // Construct using com.three.core.protobuf.SubcribeRespProto.SubcribeResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.three.core.protobuf.SubcribeRespProto.internal_static_SubcribeResp_descriptor;
      }

      public com.three.core.protobuf.SubcribeRespProto.SubcribeResp getDefaultInstanceForType() {
        return com.three.core.protobuf.SubcribeRespProto.SubcribeResp.getDefaultInstance();
      }

      public com.three.core.protobuf.SubcribeRespProto.SubcribeResp build() {
        com.three.core.protobuf.SubcribeRespProto.SubcribeResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.three.core.protobuf.SubcribeRespProto.SubcribeResp buildPartial() {
        com.three.core.protobuf.SubcribeRespProto.SubcribeResp result = new com.three.core.protobuf.SubcribeRespProto.SubcribeResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgCode_ = msgCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jsonBody_ = jsonBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.three.core.protobuf.SubcribeRespProto.SubcribeResp) {
          return mergeFrom((com.three.core.protobuf.SubcribeRespProto.SubcribeResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.three.core.protobuf.SubcribeRespProto.SubcribeResp other) {
        if (other == com.three.core.protobuf.SubcribeRespProto.SubcribeResp.getDefaultInstance()) return this;
        if (other.hasMsgCode()) {
          setMsgCode(other.getMsgCode());
        }
        if (other.hasJsonBody()) {
          bitField0_ |= 0x00000002;
          jsonBody_ = other.jsonBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgCode()) {
          return false;
        }
        if (!hasJsonBody()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.three.core.protobuf.SubcribeRespProto.SubcribeResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.three.core.protobuf.SubcribeRespProto.SubcribeResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgCode_ ;
      /**
       * <code>required int32 msgCode = 1;</code>
       */
      public boolean hasMsgCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msgCode = 1;</code>
       */
      public int getMsgCode() {
        return msgCode_;
      }
      /**
       * <code>required int32 msgCode = 1;</code>
       */
      public Builder setMsgCode(int value) {
        bitField0_ |= 0x00000001;
        msgCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgCode = 1;</code>
       */
      public Builder clearMsgCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object jsonBody_ = "";
      /**
       * <code>required string jsonBody = 3;</code>
       */
      public boolean hasJsonBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string jsonBody = 3;</code>
       */
      public java.lang.String getJsonBody() {
        java.lang.Object ref = jsonBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jsonBody_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string jsonBody = 3;</code>
       */
      public com.google.protobuf.ByteString
          getJsonBodyBytes() {
        java.lang.Object ref = jsonBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string jsonBody = 3;</code>
       */
      public Builder setJsonBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jsonBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string jsonBody = 3;</code>
       */
      public Builder clearJsonBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jsonBody_ = getDefaultInstance().getJsonBody();
        onChanged();
        return this;
      }
      /**
       * <code>required string jsonBody = 3;</code>
       */
      public Builder setJsonBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jsonBody_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SubcribeResp)
    }

    // @@protoc_insertion_point(class_scope:SubcribeResp)
    private static final com.three.core.protobuf.SubcribeRespProto.SubcribeResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.three.core.protobuf.SubcribeRespProto.SubcribeResp();
    }

    public static com.three.core.protobuf.SubcribeRespProto.SubcribeResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SubcribeResp>
        PARSER = new com.google.protobuf.AbstractParser<SubcribeResp>() {
      public SubcribeResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SubcribeResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubcribeResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubcribeResp> getParserForType() {
      return PARSER;
    }

    public com.three.core.protobuf.SubcribeRespProto.SubcribeResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubcribeResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubcribeResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SubscribeResp.proto\"1\n\014SubcribeResp\022\017\n" +
      "\007msgCode\030\001 \002(\005\022\020\n\010jsonBody\030\003 \002(\tB,\n\027com." +
      "three.core.protobufB\021SubcribeRespProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SubcribeResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubcribeResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubcribeResp_descriptor,
        new java.lang.String[] { "MsgCode", "JsonBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
